### ISSUE TITLE
Workbench

### ISSUE THREAD

**Issue by aWitch-Doctor** [poqdavid/VirtualTool#2]
No player can use the workbench command. It comes up with an error in logs.

Im running the latest sponge api 5 and nucleus, if you need a full list of plugins i can provide that.

[17:39:53] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'workbench' for source EntityPlayerMP['Witch_Doctor'/405962, l='shops', x=-360.43, y=114.00, z=-208.60]: tried to access method net.minecraft.entity.player.EntityPlayerMP.func_71117_bO()V from class io.github.poqdavid.virtualtool.Utils.Invs
java.lang.IllegalAccessError: tried to access method net.minecraft.entity.player.EntityPlayerMP.func_71117_bO()V from class io.github.poqdavid.virtualtool.Utils.Invs
	at io.github.poqdavid.virtualtool.Utils.Invs.Open(Invs.java:90) ~[Invs.class:?]
	at io.github.poqdavid.virtualtool.Commands.WorkbenchCMD.execute(WorkbenchCMD.java:68) ~[WorkbenchCMD.class:?]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-5.2.0-BETA-385]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-5.2.0-BETA-385]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-5.2.0-BETA-385]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:825) ~[me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:812) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-5.2.0-BETA-385]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160) [CauseTracker.class:1.10.2-5.2.0-BETA-385]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-5.2.0-BETA-385]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:539) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-5.2.0-BETA-385]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhj000(SourceFile:4153) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1499) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by poqdavid** [comment]
You got the newest version ? also you will need minecraft 1.10.2
and here is the [line](https://github.com/poqdavid/VirtualTool/blob/master/src/main/java/io/github/poqdavid/virtualtool/Utils/Invs.java#L90) that gives you the error I don't why maybe something wrong with your setup

**Comment by aWitch-Doctor** [comment]
We are running the latest version and 1.10.2. Any suggestions on what to try to make it work? 

We are running Sponge Vanilla version 1.10.2-5.2.0-BETA-385 and these plugins. 
![winscp_2017-04-07_15-59-28](https://cloud.githubusercontent.com/assets/26104781/24819677/35df476c-1bab-11e7-8fa1-4cd6491d86ed.png)

**Comment by tylerbucher** [comment]
After being directed here by @aWitch-Doctor, a few things to note

- You build.gradle file does not work. The issue with that is the sponge start plugin (after that I don't know whats wrong with it.)
- What I can tell from this plugin, is that you are using NMS that is deobfuscated from forge version **12.18.3.2221-1.10.2**
- It also seems that you are only testing this against spongeForge, and it seems that @aWitch-Doctor is using spongeVanilla.

With all that being said it looks like the issue seems to be involved with the reobfuscation of minecraft sources (from the Forge server) which you are trying to invoke on a vanilla server from within your plugin. And to be fair it does not look like this plugin was intended to be run on spongeVanilla (I may be wrong).

If you have any questions let me know.

[Sponge says don't use NMS because of this right here](https://docs.spongepowered.org/stable/en/plugin/practices.html?highlight=nms#using-forge-or-nms-classes)

**Comment by poqdavid** [comment]
This plugin is meant to be run on Sponge Forge and yes sponge start doesn't work but wont matter in the build process

**Comment by aWitch-Doctor** [comment]
I'd like to change this to a request then, any chance of a build that will work for sponge vanilla?

**Comment by poqdavid** [comment]
Well i will try to make it universal but not yet i am working on few things
